# Generated by Django 5.0.6 on 2024-06-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('owner_types', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DocSorpbd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_certificate_number', models.CharField(max_length=50)),
                ('database_name', models.CharField(max_length=100)),
                ('request_number', models.CharField(max_length=50)),
                ('requestdate', models.DateField()),
                ('registrationdate', models.DateField()),
                ('authors', models.ManyToManyField(to='main.autor')),
                ('individual_owners', models.ManyToManyField(related_name='individual_owners', to='main.owner')),
                ('organization_owners', models.ManyToManyField(related_name='organization_owners', to='main.owner')),
            ],
        ),
    ]
