# Generated by Django 5.0.6 on 2024-06-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsorpbd',
            name='authors',
            field=models.ManyToManyField(related_name='Autors', to='main.autor'),
        ),
    ]
