# Generated by Django 5.0.6 on 2024-06-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_docsorpbd_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsorpbd',
            name='authors',
            field=models.ManyToManyField(to='main.autor'),
        ),
        migrations.CreateModel(
            name='SoftwareRegistrationCertificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=50)),
                ('software_name', models.CharField(max_length=100)),
                ('request_number', models.CharField(max_length=50)),
                ('request_date', models.DateField()),
                ('registration_date', models.DateField()),
                ('authors', models.ManyToManyField(to='main.autor')),
                ('individual_owners', models.ManyToManyField(related_name='software_individual_owners', to='main.owner')),
                ('organization_owners', models.ManyToManyField(related_name='software_organization_owners', to='main.owner')),
            ],
        ),
    ]
