# Generated by Django 5.0.6 on 2024-06-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_docsorpbd_authors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type_user', models.CharField(choices=[('пользователь', 'Пользователь'), ('менеджер', 'Менеджер'), ('админ', 'Админ')], max_length=12)),
            ],
        ),
    ]
