# Generated by Django 5.0.6 on 2024-06-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('user', 'Пользователь'), ('manager', 'Менеджер'), ('admin', 'Админ')], default='user', max_length=12),
        ),
    ]
