# Generated by Django 5.0.6 on 2024-06-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_type_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='academic_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='death_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='research_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
