# Generated by Django 5.0.6 on 2024-06-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_autor_academic_degree_autor_birth_day_autor_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='is_alive',
        ),
    ]
