# Generated by Django 5.0.6 on 2024-06-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_autor_is_alive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('journal', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('serial_number', models.IntegerField()),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('presentation_form', models.CharField(max_length=50)),
                ('publication_date', models.DateField()),
                ('authors', models.ManyToManyField(to='main.autor')),
            ],
        ),
    ]
