# Generated by Django 5.0.6 on 2024-06-14 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('speciality_codes', models.CharField(max_length=200, null=True)),
                ('science_fields', models.CharField(max_length=200, null=True)),
                ('level', models.CharField(choices=[('candidate', 'Кандидатская'), ('doctor', 'Докторская')], max_length=50)),
                ('organization', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.autor')),
                ('scientific_consultants', models.ManyToManyField(related_name='consultants', to='main.autor')),
                ('scientific_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to='main.autor')),
            ],
        ),
    ]
