# Generated by Django 5.0.6 on 2024-06-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_dissertation_author_dissertation_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissertation',
            name='scientific_consultants',
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='scientific_supervisor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dissertation',
            name='scientific_consultants',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
