# Generated by Django 5.0.6 on 2024-06-14 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_dissertation_scientific_consultants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissertation',
            name='scientific_consultants',
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='scientific_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to='main.autor'),
        ),
        migrations.AddField(
            model_name='dissertation',
            name='scientific_consultants',
            field=models.ManyToManyField(related_name='consultants', to='main.autor'),
        ),
    ]
