# Generated by Django 5.0.6 on 2024-06-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_dissertation_scientific_consultants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='scientific_consultants',
            field=models.ManyToManyField(null=True, related_name='consultants', to='main.autor'),
        ),
        migrations.RemoveField(
            model_name='dissertation',
            name='scientific_supervisor',
        ),
        migrations.AddField(
            model_name='dissertation',
            name='scientific_supervisor',
            field=models.ManyToManyField(null=True, related_name='supervisor', to='main.autor'),
        ),
    ]
