# Generated by Django 5.0.6 on 2024-06-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_dissertation_scientific_consultants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='p_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dissertation',
            name='p_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='docsorpbd',
            name='p_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='softwareregistrationcertificate',
            name='p_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
